CREATE TABLE food_item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    categoria ENUM('CARNE', 'LATICINIOS', 'VEGETAIS') NOT NULL,
    nome VARCHAR(255) NOT NULL,
    quantidade INT NOT NULL,
    validade DATE NOT NULL
);